name: Sync Blog Section

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/update-blog-section.yml"

permissions:
  contents: write  # Required to push changes

jobs:
  sync-blog-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Portfolio Repo
        uses: actions/checkout@v3

      - name: Fetch Blog README
        run: |
          curl -s https://raw.githubusercontent.com/Avinashgurugubelli/avi-tech-blogs/main/readme.md -o blog-readme.md

      - name: Replace Blog Section in README
        run: |
          # Extract content before START marker
          awk '/<!-- START BLOGS -->/{exit} {print}' README.md > README_tmp.md

          # Insert START marker, new blog content, END marker
          echo '<!-- START BLOGS -->' >> README_tmp.md
          cat blog-readme.md >> README_tmp.md
          echo '<!-- END BLOGS -->' >> README_tmp.md

          # Extract content after END marker (skip until END found)
          awk '/<!-- END BLOGS -->/{found=1; next} found' README.md >> README_tmp.md

          # Replace the README
          mv README_tmp.md README.md

      - name: Commit & Push if README changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔄 Auto-sync blog section from avi-tech-blogs"
          file_pattern: README.md
